[package]
name = "stacks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bip39 = "2.0.0"
bs58 = "0.4.0"
sha2 = "0.10.6"
secp256k1 = "0.27.0"
ripemd = "0.1.3"
stacks-common = "0.0.1"
hmac = "0.12.1"
thiserror = "1.0.29"