[package]
name = "stacks-rs"
version = "0.1.0"
edition = "2021"
authors = ["Max Karou <max@trustmachines.co>"]
repository = "https://github.com/mxnnn/stacks.rs"

[dependencies]
bip39 = "2.0.0"
ripemd = "0.1.3"
ring = "0.16.20"
secp256k1 = "0.27.0"
thiserror = "1.0.29"

[dev-dependencies]
rand = "0.8.5"