[package]
name = "stacks-rs"
version = "0.1.6"
edition = "2021"
license = "MIT"
authors = ["Max Karou <max@trustmachines.co>"]
repository = "https://github.com/mxnnn/stacks.rs"
description = "Rust toolkit to interact with the Stacks Blockchain."
keywords = ["stacks", "blockchain", "bitcoin"]

[dependencies]
bip39 = "2.0.0"
ripemd = "0.1.3"
ring = "0.16.20"
thiserror = "1.0.29"

[dependencies.secp256k1]
version = "0.27.0"
features = ["recovery"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.serde]
version = "1.0.160"
features = ["derive"]

[dev-dependencies]
rand = "0.8.5"

[workspace]
members = [
    "./",
    "./examples/contract-call",
    "./examples/stx-transfer",
    "./examples/broadcast-transfer",
    "./examples/call-read-only"
]