[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings", "-D", "clippy::pedantic", "-A", "clippy::must_use_candidate", "-A", "clippy::module_name_repetitions", "-A", "clippy::new_without_default"]