[workspace]
pr_labels = ["release"]
publish_timeout = "10m"
changelog_update = false

[[package]]
name = "stacks-rs"
git_tag_enable = true

[[package]]
name = "stacks_derive"
git_tag_enable = false

[[package]]
name = "stacks-tests"
release = false
publish = false
