[package]
name = "stacks-primitives"
description = ""
keywords = ["stacks", "stacks-blockchain", "bitcoin", "primitives"]
categories = ["no_std", "data-structures", "cryptography::cryptocurrencies"]
homepage = ""

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[features]
default = []
rand = ["dep:rand_core"]
serde = ["dep:serde", "bytes/serde", "hex/serde"]

[dependencies]
b58 = { workspace = true }
bytes = { workspace = true }
c32 = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
lazy-regex = { workspace = true }
rand_core = { workspace = true, optional = true }
ripemd = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }
sha2 = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
