[package]
name = "stacks-tests"
description = ""
keywords = []
categories = []
homepage = ""
publish = false

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dev-dependencies]
# workspace
stacks-primitives = { workspace = true, features = ["rand", "serde"] }

# rand
rand_core = { workspace = true }

# serde
serde_json = { workspace = true }
